using FitnessCenter.API.Models;
using Microsoft.EntityFrameworkCore;

namespace FitnessCenter.API.Data;


/// Начальные данные: администратор, категории, тренеры, абонементы, тренировки

public static class SeedData
{
    public static async Task InitializeAsync(AppDbContext context)
    {
        var changed = false;

        // ─── Совместимость схемы со старой БД без миграций ───
        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "Users"
                ADD COLUMN IF NOT EXISTS "PhotoUrl" text NULL;
            ALTER TABLE "Users"
                ADD COLUMN IF NOT EXISTS "TrainerRank" integer NULL;
            ALTER TABLE "Users"
                ADD COLUMN IF NOT EXISTS "PhoneNumber" character varying(20) NULL;

            ALTER TABLE "Trainings"
                ADD COLUMN IF NOT EXISTS "TrainerId" uuid NULL;

            CREATE INDEX IF NOT EXISTS "IX_Trainings_TrainerId"
                ON "Trainings" ("TrainerId");
            """);

        // В старых БД мог остаться обязательный CoachId. Это ломает INSERT новых тренировок,
        // если код уже перешел на TrainerId.
        await context.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Trainings'
                      AND column_name = 'CoachId'
                ) THEN
                    EXECUTE 'ALTER TABLE "Trainings" ALTER COLUMN "CoachId" DROP NOT NULL';
                END IF;
            END
            $$;
            """);

        // Таблица аудита должна существовать до любых SaveChanges, потому что
        // SaveChangesInterceptor пишет логи изменений автоматически.
        await context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AuditLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" uuid NULL,
                "EntityName" character varying(128) NOT NULL,
                "Action" character varying(16) NOT NULL,
                "Timestamp" timestamp with time zone NOT NULL,
                "OldValues" text NULL,
                "NewValues" text NULL,
                CONSTRAINT "FK_AuditLogs_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Timestamp"
                ON "AuditLogs" ("Timestamp");
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_EntityName"
                ON "AuditLogs" ("EntityName");
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Action"
                ON "AuditLogs" ("Action");
            """);

        // ─── Администратор ───
        if (!context.Users.Any(u => u.Role == "Admin"))
        {
            context.Users.Add(new User
            {
                Id = Guid.NewGuid(),
                Email = "admin@test.com",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("Admin123!"),
                Role = "Admin",
                FullName = "Администратор",
                CreatedAt = DateTime.UtcNow
            });
            changed = true;
        }

        // ─── Пользователи-тренеры ───
        if (!context.Users.Any(u => u.Role == "Trainer"))
        {
            context.Users.AddRange(
                new User
                {
                    Id = Guid.NewGuid(),
                    Email = "trainer1@test.com",
                    PasswordHash = BCrypt.Net.BCrypt.HashPassword("Trainer123!"),
                    Role = "Trainer",
                    FullName = "Алексей Воронов",
                    TrainerRank = 2,
                    CreatedAt = DateTime.UtcNow
                },
                new User
                {
                    Id = Guid.NewGuid(),
                    Email = "trainer2@test.com",
                    PasswordHash = BCrypt.Net.BCrypt.HashPassword("Trainer123!"),
                    Role = "Trainer",
                    FullName = "Марина Лебедева",
                    TrainerRank = 3,
                    CreatedAt = DateTime.UtcNow
                }
            );
            changed = true;
        }

        // ─── Категории ───
        if (!context.Categories.Any())
        {
            context.Categories.AddRange(
                new Category { Name = "Йога" },
                new Category { Name = "Кроссфит" },
                new Category { Name = "Пилатес" },
                new Category { Name = "Бокс" },
                new Category { Name = "Танцы" }
            );
            changed = true;
        }

        // ─── Абонементы ───
        if (!context.Memberships.Any())
        {
            context.Memberships.AddRange(
                new Membership
                {
                    Name = "Базовый",
                    Description = "Доступ к тренажёрному залу в дневное время",
                    Price = 2500m,
                    DurationDays = 30,
                    Options = new List<MembershipOption>
                    {
                        new() { OptionText = "Тренажёрный зал (8:00–16:00)" },
                        new() { OptionText = "Раздевалка с душем" }
                    }
                },
                new Membership
                {
                    Name = "Стандарт",
                    Description = "Полный доступ к залу и групповым занятиям",
                    Price = 4500m,
                    DurationDays = 30,
                    Options = new List<MembershipOption>
                    {
                        new() { OptionText = "Тренажёрный зал (весь день)" },
                        new() { OptionText = "Групповые занятия" },
                        new() { OptionText = "Раздевалка с сауной" }
                    }
                },
                new Membership
                {
                    Name = "Премиум",
                    Description = "VIP-доступ ко всем услугам фитнес-центра",
                    Price = 8000m,
                    DurationDays = 30,
                    Options = new List<MembershipOption>
                    {
                        new() { OptionText = "Тренажёрный зал 24/7" },
                        new() { OptionText = "Все групповые занятия" },
                        new() { OptionText = "Персональный тренер (2 занятия)" },
                        new() { OptionText = "СПА-зона и бассейн" },
                        new() { OptionText = "Полотенца и напитки" }
                    }
                }
            );
            changed = true;
        }

        if (changed) await context.SaveChangesAsync();

        await context.Database.ExecuteSqlRawAsync("""
            UPDATE "Users"
            SET "TrainerRank" = 1
            WHERE "Role" = 'Trainer' AND "TrainerRank" IS NULL;
            """);

        // EnsureCreated не добавляет новые таблицы в уже существующую БД,
        // поэтому для dev-окружения гарантируем наличие PersonalWorkouts вручную.
        await context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PersonalWorkouts" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TrainerId" uuid NOT NULL,
                "ClientId" uuid NULL,
                "DateTime" timestamp with time zone NOT NULL,
                "Price" numeric(10,2) NOT NULL,
                "Status" integer NOT NULL DEFAULT 0,
                "NotCompletedReason" character varying(500) NULL,
                CONSTRAINT "FK_PersonalWorkouts_Users_TrainerId"
                    FOREIGN KEY ("TrainerId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_PersonalWorkouts_Users_ClientId"
                    FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PersonalWorkouts_TrainerId_DateTime"
                ON "PersonalWorkouts" ("TrainerId", "DateTime");

            CREATE INDEX IF NOT EXISTS "IX_PersonalWorkouts_ClientId"
                ON "PersonalWorkouts" ("ClientId");
            """);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "PersonalWorkouts"
                ADD COLUMN IF NOT EXISTS "Status" integer NOT NULL DEFAULT 0;
            ALTER TABLE "PersonalWorkouts"
                ADD COLUMN IF NOT EXISTS "NotCompletedReason" character varying(500) NULL;

            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'PersonalWorkouts'
                      AND column_name = 'IsBooked'
                ) THEN
                    EXECUTE 'UPDATE "PersonalWorkouts" SET "Status" = CASE WHEN "IsBooked" THEN 1 ELSE 0 END WHERE "Status" = 0';
                END IF;
            END
            $$;
            """);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AiTrainerUsages" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" uuid NOT NULL,
                "UsageDate" date NOT NULL,
                "MessageCount" integer NOT NULL DEFAULT 0,
                CONSTRAINT "FK_AiTrainerUsages_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_AiTrainerUsages_UserId_UsageDate"
                ON "AiTrainerUsages" ("UserId", "UsageDate");
            """);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AiTrainerMessages" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" uuid NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_AiTrainerMessages_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_AiTrainerMessages_UserId_CreatedAt"
                ON "AiTrainerMessages" ("UserId", "CreatedAt");
            """);

        // ─── Тренировки (после сохранения категорий/тренеров) ───
        if (!context.Trainings.Any())
        {
            var cats = context.Categories.ToList();
            var trainers = context.Users.Where(u => u.Role == "Trainer").Take(2).ToList();
            var tomorrow = DateTime.UtcNow.Date.AddDays(1);

            if (trainers.Count < 2)
                throw new InvalidOperationException("Недостаточно пользователей с ролью Trainer для начального наполнения");

            context.Trainings.AddRange(
                new Training { CategoryId = cats[0].Id, TrainerId = trainers[0].Id, Description = "Утренняя йога для начинающих", StartTime = tomorrow.AddHours(8), MaxParticipants = 20 },
                new Training { CategoryId = cats[1].Id, TrainerId = trainers[1].Id, Description = "Кроссфит: интенсив", StartTime = tomorrow.AddHours(10), MaxParticipants = 15 },
                new Training { CategoryId = cats[2].Id, TrainerId = trainers[0].Id, Description = "Пилатес: укрепление core", StartTime = tomorrow.AddHours(12), MaxParticipants = 18 },
                new Training { CategoryId = cats[3].Id, TrainerId = trainers[1].Id, Description = "Бокс: основы и техника", StartTime = tomorrow.AddHours(14), MaxParticipants = 12 },
                new Training { CategoryId = cats[4].Id, TrainerId = trainers[0].Id, Description = "Зумба: танцевальная тренировка", StartTime = tomorrow.AddHours(16), MaxParticipants = 25 },
                new Training { CategoryId = cats[0].Id, TrainerId = trainers[1].Id, Description = "Вечерняя йога: расслабление", StartTime = tomorrow.AddHours(19), MaxParticipants = 20 }
            );
            await context.SaveChangesAsync();
        }

        // Если база старая и TrainerId в групповых тренировках еще не заполнен — заполним.
        var fallbackTrainer = await context.Users
            .Where(u => u.Role == "Trainer")
            .OrderBy(u => u.CreatedAt)
            .FirstOrDefaultAsync();
        if (fallbackTrainer != null)
        {
            await context.Database.ExecuteSqlRawAsync(
                """UPDATE "Trainings" SET "TrainerId" = {0} WHERE "TrainerId" IS NULL;""",
                fallbackTrainer.Id);
        }

        // ─── Слоты персональных тренировок ───
        if (!context.PersonalWorkouts.Any())
        {
            var trainers = context.Users.Where(u => u.Role == "Trainer").ToList();
            var tomorrow = DateTime.UtcNow.Date.AddDays(1);

            foreach (var trainer in trainers)
            {
                context.PersonalWorkouts.AddRange(
                    new PersonalWorkout
                    {
                        TrainerId = trainer.Id,
                        DateTime = tomorrow.AddHours(9),
                        Price = 1000m + ((Math.Clamp(trainer.TrainerRank ?? 1, 1, 5) - 1) * 500m),
                        Status = PersonalWorkoutStatus.Available
                    },
                    new PersonalWorkout
                    {
                        TrainerId = trainer.Id,
                        DateTime = tomorrow.AddHours(11),
                        Price = 1000m + ((Math.Clamp(trainer.TrainerRank ?? 1, 1, 5) - 1) * 500m),
                        Status = PersonalWorkoutStatus.Available
                    },
                    new PersonalWorkout
                    {
                        TrainerId = trainer.Id,
                        DateTime = tomorrow.AddHours(18),
                        Price = 1000m + ((Math.Clamp(trainer.TrainerRank ?? 1, 1, 5) - 1) * 500m),
                        Status = PersonalWorkoutStatus.Available
                    },
                    new PersonalWorkout
                    {
                        TrainerId = trainer.Id,
                        DateTime = DateTime.UtcNow.AddDays(-2),
                        Price = 1200m,
                        Status = PersonalWorkoutStatus.Available
                    }
                );
            }

            await context.SaveChangesAsync();
        }
    }
}
